id = "isp1807"
name = "ISP1807-LR"
vendor = "Insight SiP"
family = "nrf52"
soc = "nrf52840"
backend = "micropython-nrf"
micropython_board = "ISP1807_LR"
softdevice = "s140"
softdevice_package = "s140_nrf52_6_1_1"

[module]
flash_bytes = 1048576
ram_bytes = 262144
gpio_count = 46
has_usb = true
has_nfc = true
hfclk = "32 MHz crystal (integrated)"
lfclk = "32.768 kHz crystal (integrated)"
